Repository fastly/cli, pull requests merged in 2020-05, with the labels that each got.

#50 Ensure compute deploy selects the most ideal version to clone/activate
  pkg/compute/compute_test.go
  pkg/compute/deploy.go
Labels: bug

#55 logging: adds syslog logging endpoint
  pkg/api/interface.go
  pkg/app/run.go
  pkg/app/run_test.go
  pkg/logging/syslog/create.go
  pkg/logging/syslog/delete.go
  pkg/logging/syslog/describe.go
  pkg/logging/syslog/doc.go
  pkg/logging/syslog/list.go
  pkg/logging/syslog/root.go
  pkg/logging/syslog/syslog_test.go
  pkg/logging/syslog/update.go
  pkg/mock/api.go
Labels: enhancement

#60 Improve `compute build` rust compilation error messaging
  .gitignore
  pkg/compute/build.go
  pkg/compute/rust.go
Labels: enhancement

#67 Verify fastly crate version during compute build.
  pkg/app/run.go
  pkg/compute/build.go
  pkg/compute/compute_test.go
  pkg/compute/rust.go
  pkg/compute/testdata/build/Cargo.lock
  pkg/compute/testdata/build/Cargo.toml
  pkg/testutil/assert.go
Labels: enhancement

#56 logging: adds logentries endpoint
  pkg/api/interface.go
  pkg/app/run.go
  pkg/app/run_test.go
  pkg/logging/logentries/create.go
  pkg/logging/logentries/delete.go
  pkg/logging/logentries/describe.go
  pkg/logging/logentries/doc.go
  pkg/logging/logentries/list.go
  pkg/logging/logentries/logentries_test.go
  pkg/logging/logentries/root.go
  pkg/logging/logentries/update.go
  pkg/mock/api.go
Labels: enhancement

#57 logging: adds papertrail endpoint
  pkg/api/interface.go
  pkg/app/run.go
  pkg/app/run_test.go
  pkg/logging/papertrail/create.go
  pkg/logging/papertrail/delete.go
  pkg/logging/papertrail/describe.go
  pkg/logging/papertrail/doc.go
  pkg/logging/papertrail/list.go
  pkg/logging/papertrail/papertrail_test.go
  pkg/logging/papertrail/root.go
  pkg/logging/papertrail/update.go
  pkg/mock/api.go
Labels: enhancement

#59 logging: adds sumo logic logging endpoint
  pkg/api/interface.go
  pkg/app/run.go
  pkg/app/run_test.go
  pkg/common/command.go
  pkg/logging/sumologic/create.go
  pkg/logging/sumologic/delete.go
  pkg/logging/sumologic/describe.go
  pkg/logging/sumologic/doc.go
  pkg/logging/sumologic/list.go
  pkg/logging/sumologic/root.go
  pkg/logging/sumologic/sumologic_test.go
  pkg/logging/sumologic/update.go
  pkg/mock/api.go
Labels: enhancement

#48 Update release instructions
  .github/workflows/pr_test.yml
  Makefile
  README.md
  RELEASE.md
Labels: documentation

#72 Fallback to a file copy during update if the file rename fails
  pkg/update/root.go
Labels: bug

#62 logging: adds GCS logging endpoint
  pkg/api/interface.go
  pkg/app/run.go
  pkg/app/run_test.go
  pkg/common/command.go
  pkg/logging/gcs/create.go
  pkg/logging/gcs/delete.go
  pkg/logging/gcs/describe.go
  pkg/logging/gcs/doc.go
  pkg/logging/gcs/gcs_test.go
  pkg/logging/gcs/list.go
  pkg/logging/gcs/root.go
  pkg/logging/gcs/update.go
  pkg/mock/api.go
Labels: enhancement

#66 Basic support for historical & realtime stats
  go.mod
  pkg/api/interface.go
  pkg/app/run.go
  pkg/app/run_test.go
  pkg/config/data.go
  pkg/mock/api.go
  pkg/stats/historical.go
  pkg/stats/historical_test.go
  pkg/stats/obj.go
  pkg/stats/realtime.go
  pkg/stats/regions.go
  pkg/stats/regions_test.go
  pkg/stats/root.go
  pkg/stats/template.go
Labels: enhancement

#63 logging: adds FTP logging endpoint
  pkg/api/interface.go
  pkg/app/run.go
  pkg/app/run_test.go
  pkg/logging/ftp/create.go
  pkg/logging/ftp/delete.go
  pkg/logging/ftp/describe.go
  pkg/logging/ftp/doc.go
  pkg/logging/ftp/ftp_test.go
  pkg/logging/ftp/list.go
  pkg/logging/ftp/root.go
  pkg/logging/ftp/update.go
  pkg/mock/api.go
Labels: enhancement

#64 logging: adds Splunk endpoint
  pkg/api/interface.go
  pkg/app/run.go
  pkg/app/run_test.go
  pkg/logging/splunk/create.go
  pkg/logging/splunk/delete.go
  pkg/logging/splunk/describe.go
  pkg/logging/splunk/doc.go
  pkg/logging/splunk/list.go
  pkg/logging/splunk/root.go
  pkg/logging/splunk/splunk_test.go
  pkg/logging/splunk/update.go
  pkg/mock/api.go
Labels: enhancement

#73 logging: adds Scalyr logging endpoint support
  pkg/api/interface.go
  pkg/app/run.go
  pkg/app/run_test.go
  pkg/logging/scalyr/create.go
  pkg/logging/scalyr/delete.go
  pkg/logging/scalyr/describe.go
  pkg/logging/scalyr/doc.go
  pkg/logging/scalyr/list.go
  pkg/logging/scalyr/root.go
  pkg/logging/scalyr/scalyr_integration_test.go
  pkg/logging/scalyr/scalyr_test.go
  pkg/logging/scalyr/update.go
  pkg/mock/api.go
Labels: enhancement

#74 logging: adds Loggly logging endpoint support
  pkg/api/interface.go
  pkg/app/run.go
  pkg/app/run_test.go
  pkg/logging/loggly/create.go
  pkg/logging/loggly/delete.go
  pkg/logging/loggly/describe.go
  pkg/logging/loggly/doc.go
  pkg/logging/loggly/list.go
  pkg/logging/loggly/loggly_integration_test.go
  pkg/logging/loggly/loggly_test.go
  pkg/logging/loggly/root.go
  pkg/logging/loggly/update.go
  pkg/mock/api.go
Labels: enhancement

#75 logging: adds Honeycomb logging endpoint support
  pkg/api/interface.go
  pkg/app/run.go
  pkg/app/run_test.go
  pkg/logging/honeycomb/create.go
  pkg/logging/honeycomb/delete.go
  pkg/logging/honeycomb/describe.go
  pkg/logging/honeycomb/doc.go
  pkg/logging/honeycomb/honeycomb_integration_test.go
  pkg/logging/honeycomb/honeycomb_test.go
  pkg/logging/honeycomb/list.go
  pkg/logging/honeycomb/root.go
  pkg/logging/honeycomb/update.go
  pkg/mock/api.go
Labels: enhancement

#76 logging: adds Heroku logging endpoint support
  pkg/api/interface.go
  pkg/app/run.go
  pkg/app/run_test.go
  pkg/logging/heroku/create.go
  pkg/logging/heroku/delete.go
  pkg/logging/heroku/describe.go
  pkg/logging/heroku/doc.go
  pkg/logging/heroku/heroku_integration_test.go
  pkg/logging/heroku/heroku_test.go
  pkg/logging/heroku/list.go
  pkg/logging/heroku/root.go
  pkg/logging/heroku/update.go
  pkg/mock/api.go
Labels: enhancement

#77 logging: adds SFTP logging endpoint support
  pkg/api/interface.go
  pkg/app/run.go
  pkg/app/run_test.go
  pkg/logging/sftp/create.go
  pkg/logging/sftp/delete.go
  pkg/logging/sftp/describe.go
  pkg/logging/sftp/doc.go
  pkg/logging/sftp/list.go
  pkg/logging/sftp/root.go
  pkg/logging/sftp/sftp_integration_test.go
  pkg/logging/sftp/sftp_test.go
  pkg/logging/sftp/update.go
  pkg/mock/api.go
Labels: enhancement

#78 logging: adds Logshuttle logging endpoint support
  pkg/api/interface.go
  pkg/app/run.go
  pkg/app/run_test.go
  pkg/logging/logshuttle/create.go
  pkg/logging/logshuttle/delete.go
  pkg/logging/logshuttle/describe.go
  pkg/logging/logshuttle/doc.go
  pkg/logging/logshuttle/list.go
  pkg/logging/logshuttle/logshuttle_integration_test.go
  pkg/logging/logshuttle/logshuttle_test.go
  pkg/logging/logshuttle/root.go
  pkg/logging/logshuttle/update.go
  pkg/mock/api.go
Labels: enhancement

#79 logging: adds Cloudfiles logging endpoint support
  pkg/api/interface.go
  pkg/app/run.go
  pkg/app/run_test.go
  pkg/logging/cloudfiles/cloudfiles_integration_test.go
  pkg/logging/cloudfiles/cloudfiles_test.go
  pkg/logging/cloudfiles/create.go
  pkg/logging/cloudfiles/delete.go
  pkg/logging/cloudfiles/describe.go
  pkg/logging/cloudfiles/doc.go
  pkg/logging/cloudfiles/list.go
  pkg/logging/cloudfiles/root.go
  pkg/logging/cloudfiles/update.go
  pkg/mock/api.go
Labels: enhancement

#80 logging: adds DigitalOcean Spaces logging endpoint support
  pkg/api/interface.go
  pkg/app/run.go
  pkg/app/run_test.go
  pkg/logging/digitalocean/create.go
  pkg/logging/digitalocean/delete.go
  pkg/logging/digitalocean/describe.go
  pkg/logging/digitalocean/digitalocean_integration_test.go
  pkg/logging/digitalocean/digitalocean_test.go
  pkg/logging/digitalocean/doc.go
  pkg/logging/digitalocean/list.go
  pkg/logging/digitalocean/root.go
  pkg/logging/digitalocean/update.go
  pkg/mock/api.go
Labels: enhancement

#85 Describe subcommand consistent --name short flag -d -> -n
  pkg/app/run_test.go
  pkg/domain/describe.go
  pkg/logging/bigquery/describe.go
  pkg/logging/cloudfiles/describe.go
  pkg/logging/digitalocean/describe.go
  pkg/logging/ftp/describe.go
  pkg/logging/gcs/describe.go
  pkg/logging/heroku/describe.go
  pkg/logging/honeycomb/describe.go
  pkg/logging/logentries/describe.go
  pkg/logging/loggly/describe.go
  pkg/logging/logshuttle/describe.go
  pkg/logging/papertrail/describe.go
  pkg/logging/s3/describe.go
  pkg/logging/scalyr/describe.go
  pkg/logging/sftp/describe.go
  pkg/logging/splunk/describe.go
  pkg/logging/sumologic/describe.go
  pkg/logging/syslog/describe.go
Labels: breaking

#90 Adds Elasticsearch logging endpoint support
  pkg/api/interface.go
  pkg/app/run.go
  pkg/app/run_test.go
  pkg/logging/elasticsearch/create.go
  pkg/logging/elasticsearch/delete.go
  pkg/logging/elasticsearch/describe.go
  pkg/logging/elasticsearch/doc.go
  pkg/logging/elasticsearch/elasticsearch_integration_test.go
  pkg/logging/elasticsearch/elasticsearch_test.go
  pkg/logging/elasticsearch/list.go
  pkg/logging/elasticsearch/root.go
  pkg/logging/elasticsearch/update.go
  pkg/mock/api.go
Labels: enhancement

#89 Adds Azure Blob Storage logging endpoint support
  pkg/api/interface.go
  pkg/app/run.go
  pkg/app/run_test.go
  pkg/logging/azureblob/azureblob_integration_test.go
  pkg/logging/azureblob/azureblob_test.go
  pkg/logging/azureblob/create.go
  pkg/logging/azureblob/delete.go
  pkg/logging/azureblob/describe.go
  pkg/logging/azureblob/doc.go
  pkg/logging/azureblob/list.go
  pkg/logging/azureblob/root.go
  pkg/logging/azureblob/update.go
  pkg/mock/api.go
Labels: enhancement

#92 Adds Datadog logging endpoint support
  pkg/api/interface.go
  pkg/app/run.go
  pkg/app/run_test.go
  pkg/logging/datadog/create.go
  pkg/logging/datadog/datadog_integration_test.go
  pkg/logging/datadog/datadog_test.go
  pkg/logging/datadog/delete.go
  pkg/logging/datadog/describe.go
  pkg/logging/datadog/doc.go
  pkg/logging/datadog/list.go
  pkg/logging/datadog/root.go
  pkg/logging/datadog/update.go
  pkg/mock/api.go
Labels: enhancement

#91 Adds HTTPS logging endpoint support
  pkg/api/interface.go
  pkg/app/run.go
  pkg/app/run_test.go
  pkg/logging/https/create.go
  pkg/logging/https/delete.go
  pkg/logging/https/describe.go
  pkg/logging/https/doc.go
  pkg/logging/https/https_integration_test.go
  pkg/logging/https/https_test.go
  pkg/logging/https/list.go
  pkg/logging/https/root.go
  pkg/logging/https/update.go
  pkg/mock/api.go
Labels: enhancement

#95 Adds Kafka logging endpoint support
  pkg/api/interface.go
  pkg/app/run.go
  pkg/app/run_test.go
  pkg/logging/kafka/create.go
  pkg/logging/kafka/delete.go
  pkg/logging/kafka/describe.go
  pkg/logging/kafka/doc.go
  pkg/logging/kafka/kafka_integration_test.go
  pkg/logging/kafka/kafka_test.go
  pkg/logging/kafka/list.go
  pkg/logging/kafka/root.go
  pkg/logging/kafka/update.go
  pkg/mock/api.go
Labels: enhancement

#96 Adds Google Cloud Pub/Sub logging endpoint support
  pkg/api/interface.go
  pkg/app/run.go
  pkg/app/run_test.go
  pkg/logging/googlepubsub/create.go
  pkg/logging/googlepubsub/delete.go
  pkg/logging/googlepubsub/describe.go
  pkg/logging/googlepubsub/doc.go
  pkg/logging/googlepubsub/googlepubsub_integration_test.go
  pkg/logging/googlepubsub/googlepubsub_test.go
  pkg/logging/googlepubsub/list.go
  pkg/logging/googlepubsub/root.go
  pkg/logging/googlepubsub/update.go
  pkg/mock/api.go
Labels: enhancement
