Repository fastly/cli, pull requests merged in 2020-06, with the labels that each got.

#111 Adds ResponseCondition and Placement fields to BigQuery Creates
  pkg/app/run_test.go
  pkg/logging/bigquery/bigquery_test.go
  pkg/logging/bigquery/create.go
Labels: enhancement

#113 Adds MessageType field to GCS Updates
  pkg/app/run_test.go
  pkg/logging/gcs/gcs_test.go
  pkg/logging/gcs/update.go
Labels: enhancement

#118 Adds MessageType field to SFTP
  pkg/app/run_test.go
  pkg/logging/sftp/create.go
  pkg/logging/sftp/describe.go
  pkg/logging/sftp/list.go
  pkg/logging/sftp/sftp_integration_test.go
  pkg/logging/sftp/sftp_test.go
  pkg/logging/sftp/update.go
Labels: enhancement

#117 Adds User field to Cloudfiles Updates
  pkg/app/run_test.go
  pkg/logging/cloudfiles/cloudfiles_test.go
  pkg/logging/cloudfiles/update.go
Labels: enhancement

#116 Adds Region field to Scalyr
  pkg/app/run_test.go
  pkg/logging/scalyr/create.go
  pkg/logging/scalyr/describe.go
  pkg/logging/scalyr/list.go
  pkg/logging/scalyr/scalyr_integration_test.go
  pkg/logging/scalyr/scalyr_test.go
  pkg/logging/scalyr/update.go
Labels: enhancement

#126 Add --format flag to help to output JSON.
  .goreleaser.yml
  pkg/app/run.go
  pkg/app/usage.go
  scripts/documentation.sh
Labels: documentation, enhancement

#125 Allow compute services to be initialised from an existing service ID
  pkg/app/run_test.go
  pkg/compute/compute_integration_test.go
  pkg/compute/compute_test.go
  pkg/compute/deploy.go
  pkg/compute/init.go
Labels: enhancement

#128 Fix bash completion
  README.md
  go.mod
  go.sum
  pkg/app/run.go
Labels: bug

#132 Adds OpenStack logging support
  pkg/api/interface.go
  pkg/app/run.go
  pkg/app/run_test.go
  pkg/logging/openstack/create.go
  pkg/logging/openstack/delete.go
  pkg/logging/openstack/describe.go
  pkg/logging/openstack/doc.go
  pkg/logging/openstack/list.go
  pkg/logging/openstack/openstack_integration_test.go
  pkg/logging/openstack/openstack_test.go
  pkg/logging/openstack/root.go
  pkg/logging/openstack/update.go
  pkg/mock/api.go
Labels: enhancement
