Repository fastly/cli, pull requests merged in 2021-03, with the labels that each got.

#212 Replace deprecated ioutil functions with go 1.16.
  .github/workflows/pr_test.yml
  .github/workflows/tag_release.yml
  README.md
  go.mod
  go.sum
  pkg/app/run.go
  pkg/app/usage.go
  pkg/compute/compute_integration_test.go
  pkg/compute/compute_test.go
  pkg/compute/rust.go
  pkg/configure/configure_test.go
  pkg/edgedictionaryitem/batch.go
  pkg/logs/tail.go
  pkg/logs/tail_test.go
  pkg/testutil/file.go
Labels: enhancement

#211 Replace TOML parser
  README.md
  go.mod
  go.sum
  pkg/compute/manifest/manifest.go
  pkg/compute/rust.go
  pkg/config/data.go
  pkg/configure/configure_test.go
Labels: enhancement

#210 Implement manifest_version into the fastly.toml
  pkg/compute/compute_integration_test.go
  pkg/compute/manifest/manifest.go
  pkg/compute/manifest/manifest_test.go
  pkg/compute/testdata/init/fastly-invalid-missing-version.toml
  pkg/compute/testdata/init/fastly-invalid-unrecognised.toml
  pkg/compute/testdata/init/fastly-invalid-version-exceeded.toml
  pkg/compute/testdata/init/fastly-valid-integer.toml
  pkg/compute/testdata/init/fastly-valid-semver.toml
  pkg/errors/errors.go
Labels: enhancement

#187 Dynamic Configuration
  README.md
  cmd/fastly/main.go
  pkg/check/check.go
  pkg/compute/assemblyscript.go
  pkg/compute/build.go
  pkg/compute/compute_integration_test.go
  pkg/compute/compute_test.go
  pkg/compute/init.go
  pkg/compute/manifest/manifest.go
  pkg/compute/rust.go
  pkg/config/data.go
  pkg/configure/configure_test.go
  pkg/configure/root.go
  pkg/filesystem/directory.go
  pkg/update/check.go
  pkg/update/check_test.go
  pkg/update/root.go
Labels: enhancement

#216 Fix duplicate warning messages and missing SetOutput().
  pkg/compute/build.go
  pkg/compute/manifest/manifest.go
Labels: bug

#220 Update the fastly.toml manifest if missing manifest_version.
  Makefile
  pkg/compute/manifest/manifest.go
  pkg/compute/manifest/manifest_test.go
Labels: bug

#222 Remove version from fastly.toml manifest.
  pkg/compute/compute_integration_test.go
  pkg/compute/deploy.go
  pkg/compute/init.go
  pkg/compute/manifest/manifest.go
Labels: enhancement

#221 Don't run "cargo update" before building rust app.
  pkg/compute/rust.go
Labels: enhancement

#223 Loading remote config.toml should fail gracefully.
  cmd/fastly/main.go
  pkg/config/data.go
Labels: bug, enhancement

#225 Fix manifest_version as a section bug.
  pkg/compute/manifest/manifest.go
  pkg/compute/manifest/manifest_test.go
  pkg/compute/testdata/init/fastly-invalid-section-version.toml
  pkg/errors/errors.go
Labels: bug

#228 Set GOVERSION for goreleaser.
  .github/workflows/tag_release.yml
Labels: bug

#229 Extra error handling around loading remote configuration data.
  cmd/fastly/main.go
  pkg/check/check.go
  pkg/config/data.go
  pkg/update/check_test.go
Labels: enhancement

#233 Avoid setting fields that cause API to fail when given zero value.
  pkg/backend/update.go
Labels: bug

#234 Default to port 443 if UseSSL set.
  pkg/backend/backend_test.go
  pkg/backend/create.go
Labels: enhancement

#238 pkg/logs: fix typo in error message
  pkg/logs/tail.go
Labels: bug

#236 Make GitHub Versioner configurable.
  cmd/fastly/main.go
  pkg/app/run.go
  pkg/app/run_test.go
  pkg/backend/backend_test.go
  pkg/compute/compute_integration_test.go
  pkg/configure/configure_test.go
  pkg/domain/domain_test.go
  pkg/edgedictionary/edgedictionary_test.go
  pkg/edgedictionaryitem/edgedictionaryitem_test.go
  pkg/healthcheck/healthcheck_test.go
  pkg/logging/azureblob/azureblob_integration_test.go
  pkg/logging/bigquery/bigquery_integration_test.go
  pkg/logging/cloudfiles/cloudfiles_integration_test.go
  pkg/logging/datadog/datadog_integration_test.go
  pkg/logging/digitalocean/digitalocean_integration_test.go
  pkg/logging/elasticsearch/elasticsearch_integration_test.go
  pkg/logging/ftp/ftp_integration_test.go
  pkg/logging/gcs/gcs_integration_test.go
  pkg/logging/googlepubsub/googlepubsub_integration_test.go
  pkg/logging/heroku/heroku_integration_test.go
  pkg/logging/honeycomb/honeycomb_integration_test.go
  pkg/logging/https/https_integration_test.go
  pkg/logging/kafka/kafka_integration_test.go
  pkg/logging/kinesis/kinesis_integration_test.go
  pkg/logging/logentries/logentries_integration_test.go
  pkg/logging/loggly/loggly_integration_test.go
  pkg/logging/logshuttle/logshuttle_integration_test.go
  pkg/logging/openstack/openstack_integration_test.go
  pkg/logging/papertrail/papertrail_integration_test.go
  pkg/logging/s3/s3_integration_test.go
  pkg/logging/scalyr/scalyr_integration_test.go
  pkg/logging/sftp/sftp_integration_test.go
  pkg/logging/splunk/splunk_integration_test.go
  pkg/logging/sumologic/sumologic_integration_test.go
  pkg/logging/syslog/syslog_integration_test.go
  pkg/service/service_test.go
  pkg/serviceversion/serviceversion_test.go
  pkg/stats/historical_test.go
  pkg/stats/regions_test.go
  pkg/update/check.go
  pkg/update/check_test.go
  pkg/update/root.go
  pkg/update/versioner.go
  pkg/version/version_test.go
  pkg/whoami/whoami_test.go
Labels: enhancement

#239 Retain RUSTFLAGS values from the environment
  pkg/compute/rust.go
Labels: enhancement
