Repository fastly/cli, pull requests merged in 2021-04, with the labels that each got.

#244 Print all commands and subcommands in usage
  pkg/app/usage.go
Labels: bug

#242 Add `compute publish` subcommand.
  Makefile
  pkg/app/run.go
  pkg/app/run_test.go
  pkg/compute/build.go
  pkg/compute/compute_integration_test.go
  pkg/compute/compute_test.go
  pkg/compute/deploy.go
  pkg/compute/publish.go
Labels: enhancement

#240 Allow local binary to be renamed.
  pkg/update/versioner.go
Labels: enhancement

#245 Prepend fastly.toml reference link to manifest
  pkg/compute/manifest/manifest.go
  pkg/compute/manifest/manifest_test.go
Labels: documentation

#249 Remove flaky test logic.
  pkg/compute/manifest/manifest_test.go
  pkg/compute/testdata/init/fastly-missing-spec-url.toml
Labels: bug

#247 Warn on empty directory
  pkg/app/run_test.go
  pkg/compute/compute_integration_test.go
  pkg/compute/init.go
  pkg/errors/remediation_error.go
Labels: enhancement

#248 Check the rustup version
  pkg/compute/compute_integration_test.go
  pkg/compute/rust.go
  pkg/config/data.go
  pkg/configure/configure_test.go
Labels: bug

#253 Support usage of IAM role in S3 and Kinesis logging endpoints
  go.mod
  go.sum
  pkg/app/run_test.go
  pkg/logging/s3/create.go
  pkg/logging/s3/describe.go
  pkg/logging/s3/list.go
  pkg/logging/s3/s3_integration_test.go
  pkg/logging/s3/s3_test.go
  pkg/logging/s3/update.go
Labels: enhancement

#251 Add support for file_max_bytes configuration for azure logging endpoint
  pkg/app/run_test.go
  pkg/logging/azureblob/azureblob_integration_test.go
  pkg/logging/azureblob/create.go
  pkg/logging/azureblob/describe.go
  pkg/logging/azureblob/list.go
  pkg/logging/azureblob/update.go
Labels: enhancement

#255 Support usage of IAM role in Kinesis logging endpoint
  pkg/app/run_test.go
  pkg/logging/kinesis/create.go
  pkg/logging/kinesis/describe.go
  pkg/logging/kinesis/kinesis_integration_test.go
  pkg/logging/kinesis/kinesis_test.go
  pkg/logging/kinesis/list.go
  pkg/logging/kinesis/update.go
Labels: enhancement

#190 Add support for compression_codec to logging file sink endpoints
  pkg/app/run_test.go
  pkg/logging/azureblob/azureblob_integration_test.go
  pkg/logging/azureblob/azureblob_test.go
  pkg/logging/azureblob/create.go
  pkg/logging/azureblob/describe.go
  pkg/logging/azureblob/list.go
  pkg/logging/azureblob/update.go
  pkg/logging/cloudfiles/cloudfiles_integration_test.go
  pkg/logging/cloudfiles/cloudfiles_test.go
  pkg/logging/cloudfiles/create.go
  pkg/logging/cloudfiles/update.go
  pkg/logging/digitalocean/create.go
  pkg/logging/digitalocean/digitalocean_integration_test.go
  pkg/logging/digitalocean/digitalocean_test.go
  pkg/logging/digitalocean/update.go
  pkg/logging/ftp/create.go
  pkg/logging/ftp/describe.go
  pkg/logging/ftp/ftp_integration_test.go
  pkg/logging/ftp/ftp_test.go
  pkg/logging/ftp/list.go
  pkg/logging/ftp/update.go
  pkg/logging/gcs/create.go
  pkg/logging/gcs/describe.go
  pkg/logging/gcs/gcs_integration_test.go
  pkg/logging/gcs/gcs_test.go
  pkg/logging/gcs/list.go
  pkg/logging/gcs/update.go
  pkg/logging/openstack/create.go
  pkg/logging/openstack/describe.go
  pkg/logging/openstack/list.go
  pkg/logging/openstack/openstack_integration_test.go
  pkg/logging/openstack/openstack_test.go
  pkg/logging/openstack/update.go
  pkg/logging/s3/create.go
  pkg/logging/s3/describe.go
  pkg/logging/s3/list.go
  pkg/logging/s3/s3_integration_test.go
  pkg/logging/s3/s3_test.go
  pkg/logging/s3/update.go
  pkg/logging/sftp/create.go
  pkg/logging/sftp/describe.go
  pkg/logging/sftp/list.go
  pkg/logging/sftp/sftp_integration_test.go
  pkg/logging/sftp/sftp_test.go
  pkg/logging/sftp/update.go
Labels: enhancement

#257 Check when binary was updated.
  cmd/fastly/main.go
  pkg/app/run.go
  pkg/check/check.go
  pkg/config/data.go
  pkg/configure/configure_test.go
  pkg/revision/revision.go
  pkg/revision/revision_test.go
  pkg/update/root.go
Labels: bug

#260 Fix bug where legacy creds are reset after call to configure subcommand.
  pkg/config/data.go
Labels: bug

#267 Add isBool to command flags
  pkg/app/usage.go
Labels: enhancement
