Repository fastly/cli, pull requests merged in 2021-11, with the labels that each got.

#453 Ignore possible `rustup` output in `rustc --version`. Closes #452
  pkg/commands/compute/language_rust.go
Labels: bug

#455 Bump goreleaser to avoid Homebrew warning
  .github/workflows/tag_release.yml
Labels: bug

#454 Prevent `.Hidden()` flags/commands from being documented via `--format json`
  pkg/app/usage.go
Labels: bug

#461 Rename `--force` to `--skip-verification`
  pkg/app/run_test.go
  pkg/commands/compute/build.go
  pkg/commands/compute/publish.go
  pkg/commands/compute/serve.go
  pkg/commands/configure/root.go
  pkg/commands/service/create.go
Labels: enhancement, breaking, v1.0.0

#460 Rename `fastly compute ... --path` flags
  pkg/app/run_test.go
  pkg/commands/compute/deploy.go
  pkg/commands/compute/deploy_test.go
  pkg/commands/compute/init.go
  pkg/commands/compute/init_test.go
  pkg/commands/compute/pack.go
  pkg/commands/compute/pack_test.go
  pkg/commands/compute/publish.go
  pkg/commands/compute/update.go
  pkg/commands/compute/update_test.go
  pkg/commands/compute/validate.go
  pkg/commands/compute/validate_test.go
  pkg/testutil/env.go
Labels: enhancement, breaking, v1.0.0

#459 Rename `dictionaryitem` to `dictionary-item`
  pkg/app/commands.go
  pkg/app/run_test.go
  pkg/commands/dictionary/create.go
  pkg/commands/dictionary/delete.go
  pkg/commands/dictionary/describe.go
  pkg/commands/dictionary/dictionary_test.go
  pkg/commands/dictionary/list.go
  pkg/commands/dictionary/root.go
  pkg/commands/dictionary/update.go
  pkg/commands/dictionaryitem/create.go
  pkg/commands/dictionaryitem/delete.go
  pkg/commands/dictionaryitem/describe.go
  pkg/commands/dictionaryitem/dictionaryitem_test.go
  pkg/commands/dictionaryitem/list.go
  pkg/commands/dictionaryitem/root.go
  pkg/commands/dictionaryitem/update.go
  pkg/commands/edgedictionaryitem/batch.go
  pkg/commands/edgedictionaryitem/list.go
Labels: enhancement, breaking, v1.0.0

#456 Rename `logs tail` to `log-tail`
  pkg/app/commands.go
  pkg/app/run_test.go
  pkg/commands/logs/doc.go
  pkg/commands/logs/root.go
  pkg/commands/logtail/root.go
  pkg/commands/logtail/tail_test.go
  pkg/commands/logtail/testdata/response.json
Labels: enhancement, breaking, v1.0.0

#447 Use `EnumsVar` for `auth-token --scope`
  pkg/app/run_test.go
  pkg/commands/authtoken/authtoken_test.go
  pkg/commands/authtoken/create.go
Labels: enhancement, breaking, v1.0.0

#465 Fix: git repo as a value broken when selecting starter kit
  pkg/commands/compute/init.go
Labels: bug

#464 Implement `--watch` flag for `compute serve`
  .gitignore
  Makefile
  go.mod
  go.sum
  pkg/app/run_test.go
  pkg/commands/compute/build.go
  pkg/commands/compute/compute_test.go
  pkg/commands/compute/publish.go
  pkg/commands/compute/serve.go
  pkg/errors/errors.go
  pkg/errors/remediation_error.go
  pkg/exec/exec.go
Labels: enhancement

#469 Set defaults for backend creation
  pkg/commands/backend/create.go
  pkg/commands/compute/setup/backend.go
Labels: bug

#470 Fix error extracting package files from `.tgz` archive
  pkg/commands/compute/deploy.go
  pkg/commands/compute/init.go
  pkg/commands/compute/manifest/manifest.go
  pkg/errors/errors.go
  pkg/file/archive.go
Labels: bug

#472 Implement `SEE ALSO` section in help output
  pkg/app/run_test.go
  pkg/app/usage.go
Labels: enhancement

#473 Add command 'API' metadata
  pkg/app/metadata.json
  pkg/app/run_test.go
  pkg/app/usage.go
  pkg/commands/backend/backend_test.go
  pkg/commands/backend/update.go
  pkg/commands/compute/init.go
  pkg/commands/compute/language_rust.go
  pkg/commands/vcl/snippet/create.go
  pkg/commands/vcl/snippet/snippet_test.go
  pkg/commands/vcl/snippet/update.go
Labels: enhancement

#480 Implement custom build operation
  pkg/commands/compute/build.go
  pkg/commands/compute/build_test.go
  pkg/commands/compute/compute_test.go
  pkg/commands/compute/init.go
  pkg/commands/compute/language.go
  pkg/commands/compute/language_assemblyscript.go
  pkg/commands/compute/language_javascript.go
  pkg/commands/compute/language_rust.go
  pkg/commands/compute/manifest/manifest.go
  pkg/errors/log.go
Labels: enhancement
