Repository fastly/cli, pull requests merged in 2021-09, with the labels that each got.

#371 Update rust toolchain validation steps
  .github/workflows/pr_test.yml
  RELEASE.md
  TESTING.md
  go.mod
  pkg/commands/compute/build_test.go
  pkg/commands/compute/deploy_test.go
  pkg/commands/compute/language_rust.go
Labels: bug, enhancement

#381 Update dependency to avoid dependabot warning in GitHub UI
  cmd/fastly/static/config.toml
  go.mod
  go.sum
Labels: security

#380 validate package size doesn't exceed limit
  pkg/commands/compute/deploy.go
  pkg/commands/compute/deploy_test.go
  pkg/errors/remediation_error.go
Labels: enhancement

#382 update CLI config using flag on `update` command
  pkg/commands/update/root.go
  pkg/config/data.go
Labels: enhancement

#262 GitHub Packages support via goreleaser.
  .goreleaser.yml
  Dockerfile-assemblyscript
  Dockerfile-rust
Labels: enhancement

#394 Add support for override_host
  pkg/commands/compute/manifest/manifest.go
  pkg/commands/compute/testdata/init/fastly-viceroy-update.toml
Labels: enhancement

#395 Teach the manifest about dictionaries
  pkg/commands/compute/manifest/manifest.go
  pkg/commands/compute/testdata/init/fastly-viceroy-update.toml
Labels: enhancement

#401 Sanitise name when packing the wasm file
  pkg/commands/compute/build_test.go
  pkg/commands/compute/pack.go
  pkg/commands/compute/pack_test.go
Labels: bug

#402 Integrate domain validation
  go.mod
  go.sum
  pkg/api/interface.go
  pkg/app/run.go
  pkg/app/run_test.go
  pkg/commands/domain/domain_test.go
  pkg/commands/domain/validate.go
  pkg/mock/api.go
Labels: enhancement

#405 Use a non-interactive progress writer in non-TTY environments
  go.mod
  go.sum
  pkg/commands/compute/build.go
  pkg/commands/compute/deploy.go
  pkg/commands/compute/init.go
  pkg/commands/compute/pack.go
  pkg/commands/compute/serve.go
  pkg/commands/compute/update.go
  pkg/commands/configure/root.go
  pkg/commands/update/root.go
  pkg/text/progress.go
Labels: bug

#403 Refactor Versioner `GitHub.Download()` logic.
  go.mod
  go.sum
  pkg/commands/update/versioner.go
Labels: enhancement

#406 Implement `user` commands
  go.mod
  go.sum
  pkg/api/interface.go
  pkg/app/run.go
  pkg/app/run_test.go
  pkg/commands/domain/domain_test.go
  pkg/commands/domain/validate.go
  pkg/commands/user/create.go
  pkg/commands/user/delete.go
  pkg/commands/user/describe.go
  pkg/commands/user/doc.go
  pkg/commands/user/list.go
  pkg/commands/user/root.go
  pkg/commands/user/update.go
  pkg/commands/user/user_test.go
  pkg/mock/api.go
  scripts/scaffold-update-interfaces.sh
Labels: enhancement

#418 Clarify Starter Kit options in `compute init` flow
  pkg/commands/compute/init.go
  pkg/config/data.go
  pkg/config/data_test.go
  pkg/config/testdata/config.toml
  pkg/config/testdata/static/config.toml
  pkg/text/text.go
Labels: enhancement

#422 Provide better remediation for unrecognised `manifest_version`
  pkg/commands/compute/build.go
  pkg/commands/compute/manifest/manifest.go
  pkg/commands/compute/manifest/manifest_test.go
  pkg/errors/errors.go
  pkg/errors/remediation_error.go
Labels: bug

#425 add missing description for `user list --customer-id`
  pkg/app/run_test.go
  pkg/commands/user/list.go
Labels: bug
