Repository fastly/cli, pull requests merged in 2021-08, with the labels that each got.

#360 Refactor code to help CI performance
  .github/workflows/pr_test.yml
  .github/workflows/tag_release.yml
  pkg/commands/compute/build_test.go
  pkg/commands/compute/compute_publish_test.go
  pkg/commands/compute/compute_test.go
  pkg/commands/compute/deploy_test.go
  pkg/commands/compute/init_test.go
  pkg/commands/compute/pack_test.go
  pkg/commands/compute/update_test.go
  pkg/commands/compute/validate_test.go
  pkg/testutil/env.go
Labels: enhancement

#355 Implement `[setup]` configuration for backends
  pkg/app/run_test.go
  pkg/commands/compute/compute_mocks_test.go
  pkg/commands/compute/deploy.go
  pkg/commands/compute/deploy_test.go
  pkg/commands/compute/manifest/manifest.go
  pkg/commands/compute/publish.go
  pkg/testutil/assert.go
Labels: enhancement

#366 Omit messaging when using `--accept-defaults`
  cmd/fastly/static/config.toml
  pkg/commands/compute/deploy.go
Labels: enhancement

#368 Add executable permissions to Viceroy binary AFTER moving it
  pkg/commands/compute/serve.go
Labels: bug

#370 Refactor `compute deploy` logic to better support [setup] configuration
  .github/workflows/pr_test.yml
  TESTING.md
  pkg/commands/compute/build_test.go
  pkg/commands/compute/deploy.go
  pkg/commands/compute/deploy_test.go
  pkg/commands/compute/validate.go
Labels: bug, enhancement

#372 support Windows arm64
  .goreleaser.yml
Labels: enhancement

#374 pkg/commands/logs: respect --endpoint
  pkg/app/run_test.go
  pkg/commands/logs/tail.go
Labels: enhancement
