Repository fastly/cli, pull requests merged in 2022-10, with the labels that each got.

#549 Add account name args. Needs go-fastly update
  pkg/commands/logging/gcs/create.go
  pkg/commands/logging/gcs/describe.go
  pkg/commands/logging/gcs/gcs_integration_test.go
  pkg/commands/logging/gcs/list.go
  pkg/commands/logging/gcs/update.go
Labels: enhancement

#656 Fix JS dependency lookup
  pkg/commands/compute/language_javascript.go
Labels: bug

#658 Fix Rust output regression
  pkg/commands/compute/language_rust.go
Labels: bug

#661 Fix Rust validation step for fastly crate dependency
  pkg/commands/compute/language_rust.go
Labels: bug

#665 Ensure the `./bin` directory is present even with `--skip-verification`
  go.sum
  pkg/commands/compute/build.go
  pkg/commands/compute/build_test.go
  pkg/commands/compute/language_toolchain.go
Labels: bug

#662 Fix `compute pack` to produce expected `package.tar.gz` file name
  go.mod
  go.sum
  pkg/commands/compute/build.go
  pkg/commands/compute/pack.go
  pkg/commands/compute/pack_test.go
Labels: bug

#672 handle --help with no arguments. fixes #154
  pkg/app/usage.go
Labels: bug

#670 pkg: add objectstore API calls
  pkg/api/interface.go
  pkg/app/commands.go
  pkg/app/run_test.go
  pkg/commands/objectstore/create.go
  pkg/commands/objectstore/delete.go
  pkg/commands/objectstore/doc.go
  pkg/commands/objectstore/getkey.go
  pkg/commands/objectstore/insert.go
  pkg/commands/objectstore/keys.go
  pkg/commands/objectstore/list.go
  pkg/commands/objectstore/root.go
  pkg/mock/api.go
  pkg/text/objectstore.go
Labels: enhancement

#678 Remove upper limit on go toolchain
  .fastly/config.toml
Labels: enhancement

#683 Fix runtime panic
  pkg/cmd/cmd.go
Labels: bug

#685 Code clean up
  .fastly/config.toml
  pkg/config/config.go
Labels: clean-up

#689 Skip exit code 1 for 'help' output
  cmd/fastly/main.go
  pkg/app/usage.go
  pkg/commands/compute/build_test.go
  pkg/errors/exit_error.go
Labels: enhancement

#688 Fix release process
  .fastly/config.toml
  .github/workflows/pr_test.yml
  .github/workflows/tag_release.yml
  .gitignore
  DEVELOP.md
  Makefile
  pkg/config/config.go
  pkg/config/config_test.go
  scripts/config.sh
  scripts/release-commits.sh
Labels: enhancement

#690 Implement `--quiet` flag
  pkg/app/run.go
  pkg/app/usage.go
  pkg/cmd/cmd.go
  pkg/commands/authtoken/list.go
  pkg/commands/compute/init.go
  pkg/commands/ip/root.go
  pkg/commands/objectstore/getkey.go
  pkg/commands/objectstore/insert.go
  pkg/commands/service/update.go
  pkg/commands/update/check.go
  pkg/commands/update/check_test.go
  pkg/config/config.go
  pkg/manifest/manifest.go
  pkg/profile/profile.go
  pkg/text/objectstore.go
  scripts/config.sh
Labels: enhancement

#693 Fix runtime panic caused by missing global flags
  Makefile
  pkg/app/run.go
  pkg/app/usage.go
  pkg/cmd/cmd.go
Labels: bug

#694 Make a build quiet
  pkg/commands/compute/build.go
Labels: enhancement

#695 Add missing --help flag to globals
  pkg/cmd/cmd.go
Labels: bug

#696 Fix check for mutual exclusion flags
  pkg/cmd/cmd.go
Labels: bug

#698 Add PrintLines to text package and use in logging
  pkg/commands/logging/azureblob/azureblob_integration_test.go
  pkg/commands/logging/azureblob/describe.go
  pkg/commands/logging/bigquery/bigquery_integration_test.go
  pkg/commands/logging/bigquery/describe.go
  pkg/commands/logging/cloudfiles/cloudfiles_integration_test.go
  pkg/commands/logging/cloudfiles/describe.go
  pkg/commands/logging/datadog/datadog_integration_test.go
  pkg/commands/logging/datadog/describe.go
  pkg/commands/logging/digitalocean/describe.go
  pkg/commands/logging/digitalocean/digitalocean_integration_test.go
  pkg/commands/logging/elasticsearch/describe.go
  pkg/commands/logging/elasticsearch/elasticsearch_integration_test.go
  pkg/commands/logging/ftp/describe.go
  pkg/commands/logging/ftp/ftp_integration_test.go
  pkg/commands/logging/gcs/describe.go
  pkg/commands/logging/gcs/gcs_integration_test.go
  pkg/commands/logging/googlepubsub/describe.go
  pkg/commands/logging/googlepubsub/googlepubsub_integration_test.go
  pkg/commands/logging/heroku/describe.go
  pkg/commands/logging/heroku/heroku_integration_test.go
  pkg/commands/logging/honeycomb/describe.go
  pkg/commands/logging/honeycomb/honeycomb_integration_test.go
  pkg/commands/logging/https/describe.go
  pkg/commands/logging/https/https_integration_test.go
  pkg/commands/logging/kafka/describe.go
  pkg/commands/logging/kafka/kafka_integration_test.go
  pkg/commands/logging/kinesis/describe.go
  pkg/commands/logging/kinesis/kinesis_integration_test.go
  pkg/commands/logging/logentries/describe.go
  pkg/commands/logging/logentries/logentries_integration_test.go
  pkg/commands/logging/loggly/describe.go
  pkg/commands/logging/loggly/loggly_integration_test.go
  pkg/commands/logging/logshuttle/describe.go
  pkg/commands/logging/logshuttle/logshuttle_integration_test.go
  pkg/commands/logging/newrelic/describe.go
  pkg/commands/logging/newrelic/newrelic_test.go
  pkg/commands/logging/openstack/describe.go
  pkg/commands/logging/openstack/openstack_integration_test.go
  pkg/commands/logging/papertrail/describe.go
  pkg/commands/logging/papertrail/papertrail_integration_test.go
  pkg/commands/logging/s3/describe.go
  pkg/commands/logging/s3/s3_integration_test.go
  pkg/commands/logging/scalyr/describe.go
  pkg/commands/logging/scalyr/scalyr_integration_test.go
  pkg/commands/logging/sftp/describe.go
  pkg/commands/logging/sftp/sftp_integration_test.go
  pkg/commands/logging/splunk/describe.go
  pkg/commands/logging/splunk/splunk_integration_test.go
  pkg/commands/logging/sumologic/describe.go
  pkg/commands/logging/sumologic/sumologic_integration_test.go
  pkg/commands/logging/syslog/describe.go
  pkg/commands/logging/syslog/syslog_integration_test.go
  pkg/text/lines.go
  pkg/text/lines_test.go
Labels: enhancement
