Repository fastly/cli, pull requests merged in 2022-06, with the labels that each got.

#577 Fix typo ouput -> output
  pkg/text/progress.go
Labels: documentation

#579 Makefile: when building binary, depend on .go files
  Makefile
Labels: enhancement

#581 Support `fastly --help <command>` format
  pkg/app/usage.go
Labels: bug

#578 Implement `profile token` command
  Makefile
  pkg/app/commands.go
  pkg/app/run_test.go
  pkg/commands/profile/create.go
  pkg/commands/profile/profile_test.go
  pkg/commands/profile/token.go
Labels: enhancement

#583 Fix `compute publish --non-interactive`
  pkg/commands/compute/deploy.go
  pkg/commands/compute/deploy_test.go
  pkg/commands/compute/setup/backend.go
  pkg/commands/compute/setup/dictionary.go
  pkg/commands/compute/setup/domain.go
Labels: bug

#589 Fix version check
  pkg/commands/version/version_test.go
Labels: bug
