Repository fastly/cli, pull requests merged in 2022-09, with the labels that each got.

#635 Bump go-fastly to v6.5.1
  go.mod
  go.sum
Labels: enhancement

#636 update ssl-ciphers description
  pkg/app/run_test.go
  pkg/commands/backend/create.go
  pkg/commands/backend/update.go
Labels: enhancement

#637 Improve JS error message when a dependency is missing
  pkg/commands/compute/language_javascript.go
Labels: enhancement

#638 Change default service version selection behaviour
  pkg/cmd/flags.go
  pkg/cmd/flags_test.go
  pkg/commands/compute/deploy_test.go
Labels: enhancement

#641 Support for additional S3 storage classes
  pkg/app/run_test.go
  pkg/commands/logging/s3/create.go
  pkg/commands/logging/s3/s3_test.go
  pkg/commands/logging/s3/update.go
Labels: enhancement

#642 Watch all project files
  pkg/commands/compute/serve.go
Labels: enhancement

#576 Document the newly supported Datadog sites for logging
  pkg/app/run_test.go
  pkg/commands/logging/datadog/create.go
  pkg/commands/logging/datadog/update.go
Labels: enhancement

#640 Move the internal build scripts to the fastly.toml manifest
  .fastly/config.toml
  .github/workflows/pr_test.yml
  .github/workflows/tag_release.yml
  DOCUMENTATION.md
  README.md
  go.mod
  go.sum
  pkg/app/run_test.go
  pkg/app/usage.go
  pkg/commands/compute/build.go
  pkg/commands/compute/build_test.go
  pkg/commands/compute/compute_mocks_test.go
  pkg/commands/compute/compute_test.go
  pkg/commands/compute/deploy.go
  pkg/commands/compute/deploy_test.go
  pkg/commands/compute/init.go
  pkg/commands/compute/init_test.go
  pkg/commands/compute/language.go
  pkg/commands/compute/language_assemblyscript.go
  pkg/commands/compute/language_go.go
  pkg/commands/compute/language_javascript.go
  pkg/commands/compute/language_other.go
  pkg/commands/compute/language_rust.go
  pkg/commands/compute/language_toolchain.go
  pkg/commands/compute/publish.go
  pkg/commands/compute/serve.go
  pkg/commands/compute/testdata/build/go/go.mod
  pkg/commands/compute/testdata/build/rust/Cargo.toml
  pkg/config/config.go
  pkg/config/testdata/config-incompatible-config-version.toml
  pkg/config/testdata/config.toml
  pkg/config/testdata/static/config.toml
  pkg/errors/errors.go
  pkg/errors/remediation_error.go
  pkg/manifest/manifest.go
Labels: enhancement, breaking

#649 Implement `compute hashsum`
  pkg/app/commands.go
  pkg/commands/compute/deploy.go
  pkg/commands/compute/deploy_test.go
  pkg/commands/compute/hashsum.go
Labels: enhancement

#650 errors/log: be defensive against nil pointer dereference
  pkg/errors/log.go
Labels: bug
