Repository fastly/cli, pull requests merged in 2022-05, with the labels that each got.

#557 Prevent profile data from being unexpectedly deleted
  cmd/fastly/main.go
  pkg/app/run.go
  pkg/check/check.go
  pkg/commands/compute/serve.go
  pkg/commands/compute/serve_test.go
  pkg/commands/config/root.go
  pkg/commands/update/check.go
  pkg/commands/update/check_test.go
  pkg/config/data.go
  pkg/config/data_test.go
  pkg/testutil/env.go
Labels: enhancement

#565 Support `[scripts.post_build]`
  pkg/app/run_test.go
  pkg/commands/compute/build.go
  pkg/commands/compute/build_test.go
  pkg/commands/compute/init.go
  pkg/commands/compute/language.go
  pkg/commands/compute/language_assemblyscript.go
  pkg/commands/compute/language_javascript.go
  pkg/commands/compute/language_other.go
  pkg/commands/compute/language_rust.go
  pkg/commands/compute/publish.go
  pkg/commands/compute/serve.go
  pkg/manifest/manifest.go
Labels: enhancement

#566 Use the --port value if specified
  pkg/commands/backend/backend_test.go
  pkg/commands/backend/create.go
Labels: bug

#567 Support Viceroy "inline-toml" `format` and new `contents` field.
  pkg/manifest/manifest.go
Labels: enhancement

#569 Don't overwrite `file.Load` error with `nil`
  cmd/fastly/main.go
Labels: bug

#570 Add example inline-toml dictionary
  pkg/commands/compute/testdata/init/fastly-viceroy-update.toml
  pkg/manifest/testdata/fastly-viceroy-update.toml
Labels: enhancement

#568 Implement new global flags related to interactivity prompts and default values
  pkg/app/run.go
  pkg/app/run_test.go
  pkg/app/usage.go
  pkg/commands/compute/build.go
  pkg/commands/compute/build_test.go
  pkg/commands/compute/deploy.go
  pkg/commands/compute/deploy_test.go
  pkg/commands/compute/init.go
  pkg/commands/compute/publish.go
  pkg/commands/compute/serve.go
  pkg/commands/compute/setup/loggers.go
  pkg/commands/vcl/snippet/describe.go
  pkg/commands/vcl/snippet/update.go
  pkg/config/data.go
Labels: breaking
