Repository fastly/cli, pull requests merged in 2023-03, with the labels that each got.

#848 feat(dict/create): display dictionary ID on creation
  pkg/commands/dictionary/create.go
  pkg/commands/dictionary/dictionary_test.go
Labels: enhancement

#849 fix(compute/serve): ensure spinner is closed for all logic branches
  pkg/commands/compute/serve.go
  pkg/text/spinner.go
Labels: bug

#851 refactor: clean-up nil error checks
  pkg/commands/acl/describe.go
  pkg/commands/aclentry/describe.go
  pkg/commands/authtoken/describe.go
  pkg/commands/backend/describe.go
  pkg/commands/compute/deploy.go
  pkg/commands/compute/hashsum.go
  pkg/commands/compute/init.go
  pkg/commands/compute/pack.go
  pkg/commands/compute/serve.go
  pkg/commands/compute/setup/domain.go
  pkg/commands/profile/create.go
  pkg/commands/service/describe.go
  pkg/commands/serviceauth/describe.go
  pkg/commands/tls/config/describe.go
  pkg/commands/tls/custom/activation/describe.go
  pkg/commands/tls/custom/certificate/describe.go
  pkg/commands/tls/custom/privatekey/describe.go
  pkg/commands/tls/platform/describe.go
  pkg/commands/tls/subscription/describe.go
  pkg/commands/vcl/custom/describe.go
  pkg/commands/vcl/snippet/describe.go
  pkg/config/config.go
  pkg/manifest/manifest.go
Labels: clean-up

#853 fix(build): show build output with --verbose flag
  Makefile
  pkg/commands/compute/language_toolchain.go
  pkg/exec/exec.go
Labels: bug

#857 fix(profile/update): update active profile by default not the 'user' profile
  pkg/commands/profile/update.go
  pkg/profile/profile.go
Labels: enhancement

#859 fix(compute/serve): allow overriding of viceroy binary
  pkg/commands/compute/compute_test.go
  pkg/commands/compute/serve.go
  pkg/commands/compute/serve_test.go
Labels: enhancement

#860 feat(compute/deploy): check service availability
  pkg/app/run.go
  pkg/commands/compute/deploy.go
  pkg/commands/compute/deploy_test.go
  pkg/commands/compute/publish.go
  pkg/commands/compute/setup/backend.go
  pkg/commands/compute/setup/dictionary.go
  pkg/commands/compute/setup/domain.go
  pkg/commands/compute/setup/object_store.go
  pkg/manifest/manifest.go
  pkg/mock/client.go
Labels: enhancement

#862 breaking(profiles): replace `--name` with positional arg + allow global override
  pkg/commands/profile/profile_test.go
  pkg/commands/profile/token.go
Labels: breaking

#866 refactor(compute/deploy): change default port from 80 to 443
  pkg/commands/compute/build_test.go
  pkg/commands/compute/deploy_test.go
  pkg/commands/compute/setup/backend.go
Labels: enhancement

#867 fix(compute/serve): stop spinner before starting another instance
  pkg/commands/compute/serve.go
Labels: bug

#869 fix(http/client): address confusion with timeout error
  cmd/fastly/main.go
  pkg/github/github.go
Labels: bug

#870 fix(http/client): bump timeout to account for poor network conditions
  cmd/fastly/main.go
Labels: bug

#871 refactor(compute/deploy): output formatting
  pkg/commands/compute/deploy.go
Labels: enhancement

#873 fix various lint and CI issues
  .github/workflows/pr_test.yml
  .github/workflows/tag_release.yml
  pkg/commands/compute/language_toolchain.go
  pkg/commands/compute/serve.go
Labels: enhancement

#829 feat(config-store): Add Config Store commands
  go.mod
  go.sum
  pkg/api/interface.go
  pkg/app/commands.go
  pkg/app/run_test.go
  pkg/commands/backend/backend_test.go
  pkg/commands/configstore/configstore_test.go
  pkg/commands/configstore/create.go
  pkg/commands/configstore/delete.go
  pkg/commands/configstore/describe.go
  pkg/commands/configstore/doc.go
  pkg/commands/configstore/helper_test.go
  pkg/commands/configstore/list.go
  pkg/commands/configstore/list_services.go
  pkg/commands/configstore/root.go
  pkg/commands/configstore/update.go
  pkg/commands/configstoreentry/configstoreentry_test.go
  pkg/commands/configstoreentry/create.go
  pkg/commands/configstoreentry/delete.go
  pkg/commands/configstoreentry/describe.go
  pkg/commands/configstoreentry/doc.go
  pkg/commands/configstoreentry/errors.go
  pkg/commands/configstoreentry/list.go
  pkg/commands/configstoreentry/root.go
  pkg/commands/configstoreentry/update.go
  pkg/commands/secretstore/doc.go
  pkg/commands/secretstoreentry/doc.go
  pkg/mock/api.go
  pkg/text/configstore.go
Labels: enhancement

#875 fix(compute/deploy): service availability
  pkg/commands/compute/deploy.go
  pkg/commands/compute/publish.go
Labels: enhancement

#876 fix(compute/deploy): check status code range
  pkg/commands/compute/deploy.go
Labels: enhancement

#881 fix(service/create): input.Type assigned wrong value
  pkg/commands/service/create.go
Labels: bug

#886 feat(ratelimit): implement rate-limiter API
  go.mod
  go.sum
  pkg/api/interface.go
  pkg/app/commands.go
  pkg/app/run_test.go
  pkg/cmd/common.go
  pkg/commands/ratelimit/create.go
  pkg/commands/ratelimit/delete.go
  pkg/commands/ratelimit/describe.go
  pkg/commands/ratelimit/doc.go
  pkg/commands/ratelimit/list.go
  pkg/commands/ratelimit/ratelimit_test.go
  pkg/commands/ratelimit/root.go
  pkg/commands/ratelimit/update.go
  pkg/mock/api.go
Labels: enhancement

#888 build(deps): bump tinygo baseline version
  .fastly/config.toml
  Makefile
  pkg/commands/compute/build_test.go
Labels: dependencies

#889 fix(toolchain): bump go version to align with updated tinygo constraint
  .fastly/config.toml
Labels: bug

#891 feat(ratelimit): add missing properties
  go.mod
  go.sum
  pkg/commands/ratelimit/create.go
  pkg/commands/ratelimit/update.go
Labels: enhancement

#892 feat(ratelimiter): add uri-dict-name flag
  go.mod
  go.sum
  pkg/commands/ratelimit/create.go
  pkg/commands/ratelimit/update.go
Labels: enhancement
