Repository fastly/cli, pull requests merged in 2023-09, with the labels that each got.

#1012 feat(compute/build): support env_vars for JavaScript/Rust
  pkg/commands/compute/language_javascript.go
  pkg/commands/compute/language_other.go
  pkg/commands/compute/language_rust.go
  pkg/commands/compute/language_toolchain.go
Labels: enhancement

#1014 fix(compute/init): post_init to support env_vars
  pkg/commands/compute/init.go
Labels: bug

#1017 fix(DEVELOP.MD): clarify Go version requirement and document Rust requirement
  DEVELOP.md
Labels: documentation

#1021 fix(packaging): Improve metadata in Linux packages
  .goreleaser.yml
  deb-copyright
Labels: enhancement

#1022 fix(app): return error when input is `--` only
  pkg/app/usage.go
Labels: bug
