Repository fastly/cli, pull requests merged in 2023-06, with the labels that each got.

#953 ci: fix cache restore bug
  .github/workflows/pr_test.yml
Labels: bug, github_actions

#954 fix: remove sentry
  .github/workflows/tag_release.yml
  cmd/fastly/main.go
  go.mod
  go.sum
  pkg/commands/aclentry/update.go
  pkg/commands/compute/build.go
  pkg/commands/compute/deploy.go
  pkg/commands/compute/init.go
  pkg/commands/compute/pack.go
  pkg/commands/compute/update.go
  pkg/commands/compute/validate.go
  pkg/commands/dictionary/update.go
  pkg/commands/logging/bigquery/create.go
  pkg/commands/logging/bigquery/update.go
  pkg/commands/logging/cloudfiles/create.go
  pkg/commands/logging/cloudfiles/update.go
  pkg/commands/profile/create.go
  pkg/commands/profile/update.go
  pkg/commands/purge/root.go
  pkg/commands/serviceauth/create.go
  pkg/commands/stats/historical.go
  pkg/commands/update/root.go
  pkg/commands/vcl/custom/update.go
  pkg/commands/vcl/snippet/describe.go
  pkg/commands/vcl/snippet/update.go
  pkg/errors/log.go
  scripts/go-test-cache/main.go
  scripts/release-commits.sh
Labels: enhancement

#955 refactor: logic clean-up
  cmd/fastly/main.go
  pkg/manifest/file.go
Labels: enhancement, clean-up

#960 refactor(ci): disable setup-go caching to avoid later cache restoration errors
  .github/workflows/pr_test.yml
Labels: clean-up

#961 fix(update): use consistent pattern for replacing binary
  pkg/commands/update/root.go
Labels: bug

#964 fix(kvstoreentry): avoid runtime panic for out of bound slice index
  pkg/commands/kvstoreentry/create.go
Labels: bug

#967 Correctly check if the package is up to date
  pkg/commands/compute/deploy.go
  pkg/commands/compute/deploy_test.go
  pkg/commands/compute/hashfiles.go
  pkg/commands/compute/hashsum.go
  pkg/commands/compute/validate.go
Labels: bug
