Repository fastly/cli, pull requests merged in 2023-02, with the labels that each got.

#786 fix(compute/build): AssemblyScript bugs
  pkg/commands/compute/language_assemblyscript.go
Labels: bug

#785 Remove user environment validation logic
  .github/workflows/pr_test.yml
  .github/workflows/tag_release.yml
  .gitignore
  Makefile
  go.mod
  pkg/api/undocumented/undocumented.go
  pkg/commands/compute/build.go
  pkg/commands/compute/build_test.go
  pkg/commands/compute/init.go
  pkg/commands/compute/init_test.go
  pkg/commands/compute/language.go
  pkg/commands/compute/language_assemblyscript.go
  pkg/commands/compute/language_go.go
  pkg/commands/compute/language_javascript.go
  pkg/commands/compute/language_other.go
  pkg/commands/compute/language_rust.go
  pkg/commands/compute/language_toolchain.go
  pkg/commands/compute/publish.go
  pkg/commands/compute/serve.go
  pkg/commands/compute/setup/domain.go
  pkg/commands/whoami/root.go
  pkg/exec/exec.go
  pkg/filesystem/directory.go
  pkg/github/github.go
Labels: enhancement

#789 update local_server object and secret store formats
  pkg/commands/compute/testdata/init/fastly-viceroy-update.toml
  pkg/manifest/manifest.go
  pkg/manifest/testdata/fastly-viceroy-update.toml
Labels: enhancement

#797 refactor(secretstore): divide command files into separate packages
  pkg/app/commands.go
  pkg/cmd/common.go
  pkg/cmd/flags.go
  pkg/commands/secretstore/create.go
  pkg/commands/secretstore/delete.go
  pkg/commands/secretstore/deletesecret.go
  pkg/commands/secretstore/describe.go
  pkg/commands/secretstore/flags.go
  pkg/commands/secretstore/helper_test.go
  pkg/commands/secretstore/json.go
  pkg/commands/secretstore/list.go
  pkg/commands/secretstore/root.go
  pkg/commands/secretstore/secretstore_test.go
  pkg/commands/secretstoreentry/create.go
  pkg/commands/secretstoreentry/delete.go
  pkg/commands/secretstoreentry/describe.go
  pkg/commands/secretstoreentry/doc.go
  pkg/commands/secretstoreentry/flags.go
  pkg/commands/secretstoreentry/helper_test.go
  pkg/commands/secretstoreentry/list.go
  pkg/commands/secretstoreentry/root.go
  pkg/commands/secretstoreentry/secretstoreentry_test.go
  pkg/fmt/doc.go
  pkg/fmt/fmt.go
Labels: clean-up

#798 refactor(dictionaryitem): rename from item to entry
  pkg/app/commands.go
  pkg/app/run_test.go
  pkg/commands/dictionaryentry/create.go
  pkg/commands/dictionaryentry/delete.go
  pkg/commands/dictionaryentry/describe.go
  pkg/commands/dictionaryentry/dictionaryitem_test.go
  pkg/commands/dictionaryentry/doc.go
  pkg/commands/dictionaryentry/list.go
  pkg/commands/dictionaryentry/root.go
  pkg/commands/dictionaryentry/update.go
  pkg/commands/dictionaryitem/doc.go
Labels: breaking

#801 refactor(compute): add command output when there is an error
  pkg/commands/compute/language_rust.go
Labels: enhancement

#807 build(goreleaser): replace deprecated flag
  .github/workflows/tag_release.yml
Labels: clean-up

#808 fix(compute/setup): fix duplicated domains
  pkg/commands/compute/setup/domain.go
Labels: bug

#809 refactor: add type annotations
  pkg/cmd/common.go
  pkg/fmt/fmt.go
Labels: clean-up

#810 build(lint): implement semgrep for local validation
  Makefile
  pkg/api/undocumented/undocumented.go
  pkg/app/usage.go
  pkg/commands/secretstoreentry/create.go
  pkg/testutil/env.go
Labels: enhancement

#811 fix(setup/domain): allow user to correct a domain already in use
  pkg/commands/compute/deploy.go
  pkg/commands/compute/deploy_test.go
  pkg/commands/compute/setup/domain.go
Labels: bug

#814 fix(compute/build): only use default build script if none defined
  pkg/commands/compute/language_javascript.go
Labels: bug

#815 fix(compute/build): ensure build output doesn't show unless --verbose flag is set
  pkg/commands/compute/build.go
  pkg/commands/compute/language_toolchain.go
  pkg/exec/exec.go
Labels: enhancement

#816 docs: remove --skip-verification
  pkg/app/metadata.json
Labels: documentation

#820 fix(compute/deploy): replace spinner implementation
  go.mod
  go.sum
  pkg/commands/compute/deploy.go
  pkg/commands/compute/deploy_test.go
  pkg/commands/compute/setup/backend.go
  pkg/commands/compute/setup/dictionary.go
  pkg/commands/compute/setup/domain.go
  pkg/commands/compute/setup/object_store.go
  pkg/text/progress.go
Labels: bug

#824 fix(dns): migrate to go1.20
  .github/workflows/pr_test.yml
  .github/workflows/tag_release.yml
  go.mod
  pkg/commands/compute/setup/domain.go
Labels: enhancement

#826 build(goreleaser): build with explicit CGO_ENABLED=0
  .goreleaser.yml
  Makefile
Labels: bug

#832 fix(compute/serve): check for missing override_host
  pkg/commands/compute/serve.go
  pkg/commands/secretstoreentry/create.go
Labels: enhancement

#833 refactor: linter issues resolved
  pkg/commands/secretstoreentry/create.go
  pkg/text/progress.go
Labels: clean-up

#835 breaking(logging): remove logentries
  pkg/app/commands.go
  pkg/commands/logging/logentries/create.go
  pkg/commands/logging/logentries/delete.go
  pkg/commands/logging/logentries/describe.go
  pkg/commands/logging/logentries/doc.go
  pkg/commands/logging/logentries/list.go
  pkg/commands/logging/logentries/logentries_integration_test.go
  pkg/commands/logging/logentries/logentries_test.go
  pkg/commands/logging/logentries/root.go
  pkg/commands/logging/logentries/update.go
Labels: breaking

#834 fix(compute/serve): replace separate ignore files with .fastlyignore
  go.mod
  go.sum
  pkg/commands/compute/serve.go
Labels: breaking

#836 fix(compute/build): ignore all files except manifest and wasm binary
  pkg/commands/compute/build.go
Labels: bug

#839 fix(compute/serve): output rendering
  pkg/commands/compute/language_toolchain.go
  pkg/commands/compute/serve.go
  pkg/exec/exec.go
Labels: bug

#840 refactor(spinner): hide ... after spinner has stopped
  pkg/commands/compute/build.go
  pkg/commands/compute/deploy.go
  pkg/commands/compute/deploy_test.go
  pkg/commands/compute/init.go
  pkg/commands/compute/init_test.go
  pkg/commands/compute/language_assemblyscript.go
  pkg/commands/compute/language_go.go
  pkg/commands/compute/language_javascript.go
  pkg/commands/compute/language_other.go
  pkg/commands/compute/language_rust.go
  pkg/commands/compute/language_toolchain.go
  pkg/commands/compute/pack.go
  pkg/commands/compute/pack_test.go
  pkg/commands/compute/serve.go
  pkg/commands/compute/setup/backend.go
  pkg/commands/compute/setup/dictionary.go
  pkg/commands/compute/setup/domain.go
  pkg/commands/compute/setup/object_store.go
  pkg/commands/compute/update.go
  pkg/commands/compute/update_test.go
  pkg/commands/profile/create.go
  pkg/commands/profile/profile_test.go
  pkg/commands/profile/update.go
  pkg/commands/update/root.go
  pkg/text/spinner.go
Labels: enhancement

#842 Fix `compute build` rendered output
  pkg/commands/backend/create.go
  pkg/commands/compute/build.go
  pkg/commands/compute/build_test.go
  pkg/commands/compute/language_assemblyscript.go
  pkg/commands/compute/language_go.go
  pkg/commands/compute/language_javascript.go
  pkg/commands/compute/language_other.go
  pkg/commands/compute/language_rust.go
  pkg/commands/compute/language_toolchain.go
  pkg/commands/compute/serve.go
  pkg/exec/exec.go
Labels: bug

#843 fix(compute/serve): make override_host a default behaviour
  pkg/commands/compute/serve.go
Labels: enhancement

#847 fix(compute/build): move log calls before subprocess call
  pkg/commands/compute/language_go.go
  pkg/commands/compute/language_rust.go
Labels: bug
