Repository fastly/cli, pull requests merged in 2023-10, with the labels that each got.

#1023 feat(compute/build): support Cargo Workspaces
  pkg/commands/compute/language_rust.go
Labels: enhancement

#1026 fix(compute/deploy): check package before service clone
  pkg/commands/compute/deploy.go
  pkg/commands/compute/deploy_test.go
  pkg/commands/compute/hashsum.go
Labels: bug

#1029 fix: spinner wraps original error
  pkg/commands/compute/deploy.go
  pkg/commands/compute/init.go
  pkg/commands/compute/language_toolchain.go
  pkg/commands/compute/serve.go
  pkg/commands/compute/setup/backend.go
  pkg/commands/compute/setup/config_store.go
  pkg/commands/compute/setup/domain.go
  pkg/commands/compute/setup/kv_store.go
  pkg/commands/compute/setup/secret_store.go
  pkg/commands/kvstoreentry/list.go
  pkg/exec/exec.go
  pkg/text/spinner.go
Labels: bug

#1036 feat(product_enablement): add products command
  go.mod
  go.sum
  pkg/api/interface.go
  pkg/app/commands.go
  pkg/app/run_test.go
  pkg/commands/products/doc.go
  pkg/commands/products/products_test.go
  pkg/commands/products/root.go
  pkg/commands/vcl/condition/create.go
  pkg/errors/errors.go
  pkg/mock/api.go
Labels: enhancement

#1038 fix(compute/serve): formatting of line breaks
  pkg/commands/compute/serve.go
Labels: enhancement

#1032 refactor(compute/deploy): simplify logic flows
  pkg/commands/compute/deploy.go
  pkg/commands/compute/deploy_test.go
  pkg/commands/compute/hashsum.go
  pkg/commands/compute/init.go
  pkg/commands/compute/publish.go
  pkg/commands/compute/setup/domain.go
Labels: clean-up

#1043 feat(compute/build): allow user to specify project directory to build
  DEVELOP.md
  pkg/cmd/flags.go
  pkg/commands/authtoken/delete.go
  pkg/commands/compute/build.go
  pkg/commands/compute/deploy.go
  pkg/commands/compute/deploy_test.go
  pkg/commands/compute/publish.go
  pkg/commands/compute/serve.go
  pkg/commands/purge/root.go
  pkg/testutil/env.go
Labels: enhancement

#1044 branding: Replace all Compute@Edge/C@E references with Compute.
  .fastly/help/README.md
  .fastly/help/ecp-feature.mdx
  cmd/fastly/main.go
  pkg/app/metadata.json
  pkg/commands/compute/build.go
  pkg/commands/compute/deploy.go
  pkg/commands/compute/deploy_test.go
  pkg/commands/compute/doc.go
  pkg/commands/compute/hashfiles.go
  pkg/commands/compute/hashsum.go
  pkg/commands/compute/init.go
  pkg/commands/compute/language.go
  pkg/commands/compute/language_assemblyscript.go
  pkg/commands/compute/language_go.go
  pkg/commands/compute/language_javascript.go
  pkg/commands/compute/language_rust.go
  pkg/commands/compute/language_toolchain.go
  pkg/commands/compute/pack.go
  pkg/commands/compute/publish.go
  pkg/commands/compute/root.go
  pkg/commands/compute/serve.go
  pkg/commands/compute/setup/config_store.go
  pkg/commands/compute/setup/kv_store.go
  pkg/commands/compute/setup/secret_store.go
  pkg/commands/compute/testdata/build/assemblyscript/assembly/index.ts
  pkg/commands/compute/testdata/build/assemblyscript/package.json
  pkg/commands/compute/testdata/init/fastly-viceroy-update.toml
  pkg/commands/compute/update.go
  pkg/commands/compute/validate.go
  pkg/commands/logtail/root.go
  pkg/config/config.go
  pkg/errors/remediation_error.go
  pkg/manifest/file.go
  pkg/manifest/manifest.go
  pkg/manifest/testdata/fastly-viceroy-update.toml
  pkg/manifest/version.go
Labels: documentation

#1046 feat: support `--env` flag
  RELEASE.md
  pkg/app/commands.go
  pkg/commands/compute/build.go
  pkg/commands/compute/compute_test.go
  pkg/commands/compute/deploy.go
  pkg/commands/compute/dir.go
  pkg/commands/compute/hashfiles.go
  pkg/commands/compute/hashsum.go
  pkg/commands/compute/init.go
  pkg/commands/compute/language_assemblyscript.go
  pkg/commands/compute/language_go.go
  pkg/commands/compute/language_javascript.go
  pkg/commands/compute/language_other.go
  pkg/commands/compute/language_rust.go
  pkg/commands/compute/language_toolchain.go
  pkg/commands/compute/publish.go
  pkg/commands/compute/serve.go
  pkg/commands/compute/validate.go
Labels: enhancement

#1052 refactor(compute/deploy): add setup message for existing service users
  pkg/commands/compute/deploy.go
Labels: enhancement

#1053 fix(compute/deploy): ignore package comparison error
  pkg/commands/compute/deploy.go
Labels: bug

#1055 fix(backend): support disabling ssl-check-cert
  pkg/commands/backend/create.go
  pkg/commands/backend/update.go
Labels: bug

#1056 feat: add `--debug-mode`
  go.mod
  go.sum
  pkg/app/run.go
  pkg/commands/logging/azureblob/azureblob_test.go
  pkg/commands/logging/bigquery/bigquery_test.go
  pkg/commands/logging/cloudfiles/cloudfiles_test.go
  pkg/commands/logging/datadog/datadog_test.go
  pkg/commands/logging/digitalocean/digitalocean_test.go
  pkg/commands/logging/elasticsearch/elasticsearch_test.go
  pkg/commands/logging/ftp/ftp_test.go
  pkg/commands/logging/gcs/gcs_test.go
  pkg/commands/logging/googlepubsub/googlepubsub_test.go
  pkg/commands/logging/heroku/heroku_test.go
  pkg/commands/logging/honeycomb/honeycomb_test.go
  pkg/commands/logging/https/https_test.go
  pkg/commands/logging/kafka/kafka_test.go
  pkg/commands/logging/kinesis/kinesis_test.go
  pkg/commands/logging/loggly/loggly_test.go
  pkg/commands/logging/logshuttle/logshuttle_test.go
  pkg/commands/logging/openstack/openstack_test.go
  pkg/commands/logging/papertrail/papertrail_test.go
  pkg/commands/logging/s3/s3_test.go
  pkg/commands/logging/scalyr/scalyr_test.go
  pkg/commands/logging/sftp/sftp_test.go
  pkg/commands/logging/splunk/splunk_test.go
  pkg/commands/logging/sumologic/sumologic_test.go
  pkg/commands/logging/syslog/syslog_test.go
  pkg/commands/profile/create.go
  pkg/commands/profile/update.go
  pkg/commands/whoami/whoami_test.go
  pkg/global/global.go
  pkg/mock/client.go
Labels: enhancement

#1057 ci: replace setup-tinygo fork with original
  .github/workflows/pr_test.yml
Labels: dependencies, github_actions

#1058 feat: add `--consistency` flag to `kv-store-entry list` command
  go.mod
  go.sum
  pkg/app/usage.go
  pkg/commands/kvstoreentry/list.go
Labels: enhancement

#1016 feat(telemetry): add wasm-tools wasm binary annotations
  .fastly/config.toml
  .github/workflows/pr_test.yml
  cmd/fastly/main.go
  go.mod
  go.sum
  pkg/app/commands.go
  pkg/app/run.go
  pkg/commands/compute/build.go
  pkg/commands/compute/build_test.go
  pkg/commands/compute/compute_test.go
  pkg/commands/compute/hashfiles.go
  pkg/commands/compute/hashsum.go
  pkg/commands/compute/init.go
  pkg/commands/compute/language_assemblyscript.go
  pkg/commands/compute/language_go.go
  pkg/commands/compute/language_javascript.go
  pkg/commands/compute/language_other.go
  pkg/commands/compute/language_rust.go
  pkg/commands/compute/language_toolchain.go
  pkg/commands/compute/publish.go
  pkg/commands/compute/serve.go
  pkg/commands/compute/serve_test.go
  pkg/commands/version/root.go
  pkg/commands/version/version_test.go
  pkg/config/config.go
  pkg/env/env.go
  pkg/github/github.go
  pkg/global/global.go
  pkg/manifest/file.go
  pkg/mock/versioner.go
  pkg/testutil/args.go
  pkg/testutil/env.go
  pkg/text/text_test.go
Labels: enhancement

#1013 feat(compute): add `metadata` subcommand
  .fastly/config.toml
  DEVELOP.md
  pkg/app/commands.go
  pkg/app/run.go
  pkg/app/run_test.go
  pkg/commands/compute/build.go
  pkg/commands/compute/metadata.go
  pkg/commands/compute/metadata_test.go
  pkg/commands/compute/testdata/metadata/config.toml
  pkg/commands/ip/ip_test.go
  pkg/commands/products/root.go
  pkg/config/config.go
  pkg/errors/errors.go
Labels: enhancement
