Repository fastly/cli, pull requests merged in 2023-04, with the labels that each got.

#896 fix(profile): always prompt for token
  pkg/commands/profile/create.go
Labels: enhancement

#769 feat(compute/deploy): add Secret Store to manifest `[setup]`
  pkg/commands/compute/deploy.go
  pkg/commands/compute/setup/secret_store.go
  pkg/manifest/manifest.go
Labels: enhancement

#909 fix(errors/log): support allowing errors to Sentry
  pkg/commands/aclentry/update.go
  pkg/commands/compute/build.go
  pkg/commands/compute/deploy.go
  pkg/commands/compute/init.go
  pkg/commands/compute/pack.go
  pkg/commands/compute/update.go
  pkg/commands/compute/validate.go
  pkg/commands/dictionary/update.go
  pkg/commands/logging/bigquery/create.go
  pkg/commands/logging/bigquery/update.go
  pkg/commands/logging/cloudfiles/create.go
  pkg/commands/logging/cloudfiles/update.go
  pkg/commands/profile/create.go
  pkg/commands/profile/update.go
  pkg/commands/purge/root.go
  pkg/commands/serviceauth/create.go
  pkg/commands/stats/historical.go
  pkg/commands/update/root.go
  pkg/commands/vcl/custom/update.go
  pkg/commands/vcl/snippet/describe.go
  pkg/commands/vcl/snippet/update.go
  pkg/errors/log.go
Labels: enhancement

#907 Support latest fastly.toml manifest data model
  pkg/commands/compute/compute_mocks_test.go
  pkg/commands/compute/deploy.go
  pkg/commands/compute/deploy_test.go
  pkg/commands/compute/setup/config_store.go
  pkg/commands/compute/setup/dictionary.go
  pkg/errors/errors.go
  pkg/manifest/data.go
  pkg/manifest/file.go
  pkg/manifest/flags.go
  pkg/manifest/local_server.go
  pkg/manifest/manifest.go
  pkg/manifest/manifest_test.go
  pkg/manifest/setup.go
  pkg/manifest/testdata/fastly-invalid-section-version.toml
  pkg/manifest/testdata/fastly-invalid-unrecognised.toml
  pkg/manifest/testdata/fastly-missing-spec-url.toml
  pkg/manifest/testdata/fastly-valid-integer.toml
  pkg/manifest/testdata/fastly-viceroy-update.toml
  pkg/manifest/testdata/fastly-warning-dictionaries.toml
  pkg/manifest/version.go
Labels: enhancement, breaking

#911 feat(service): support --json for service search subcommand
  pkg/commands/configstore/create.go
  pkg/commands/configstore/delete.go
  pkg/commands/configstore/describe.go
  pkg/commands/configstore/list.go
  pkg/commands/configstore/list_services.go
  pkg/commands/configstore/update.go
  pkg/commands/configstoreentry/create.go
  pkg/commands/configstoreentry/delete.go
  pkg/commands/configstoreentry/describe.go
  pkg/commands/configstoreentry/list.go
  pkg/commands/configstoreentry/update.go
  pkg/commands/secretstore/create.go
  pkg/commands/secretstore/delete.go
  pkg/commands/secretstore/describe.go
  pkg/commands/secretstore/list.go
  pkg/commands/service/search.go
Labels: enhancement

#915 fix(manifest): re-raise remediation error to avoid go-toml wrapping issue
  pkg/errors/errors.go
  pkg/errors/remediation_error.go
  pkg/manifest/file.go
  pkg/manifest/manifest_test.go
Labels: bug

#916 fix(compute/deploy): shorten message to avoid spinner bug
  pkg/commands/compute/deploy.go
Labels: bug

#918 fix: reinstate support for [setup.object_stores]
  pkg/commands/compute/deploy.go
  pkg/commands/compute/setup/backend.go
  pkg/commands/compute/setup/config_store.go
  pkg/commands/compute/setup/kv_store.go
  pkg/commands/service/list.go
  pkg/manifest/file.go
  pkg/manifest/setup.go
Labels: bug

#924 fix(compute/serve): always set verbose mode for viceroy
  pkg/commands/compute/serve.go
  pkg/manifest/file.go
Labels: enhancement
