Repository fastly/cli, pull requests merged in 2023-05, with the labels that each got.

#937 refactor: make config/kv/secret store output consistent
  pkg/app/metadata.json
  pkg/commands/configstore/configstore_test.go
  pkg/commands/configstore/create.go
  pkg/commands/configstore/delete.go
  pkg/commands/configstore/update.go
  pkg/commands/configstoreentry/configstoreentry_test.go
  pkg/commands/configstoreentry/create.go
  pkg/commands/configstoreentry/delete.go
  pkg/commands/kvstore/create.go
  pkg/commands/kvstore/delete.go
  pkg/commands/kvstore/kvstore_test.go
  pkg/commands/kvstoreentry/create.go
  pkg/commands/kvstoreentry/delete.go
  pkg/commands/kvstoreentry/kvstoreentry_test.go
  pkg/commands/secretstore/create.go
  pkg/commands/secretstore/delete.go
  pkg/commands/secretstore/secretstore_test.go
  pkg/commands/secretstoreentry/create.go
  pkg/commands/secretstoreentry/delete.go
  pkg/commands/secretstoreentry/secretstoreentry_test.go
Labels: enhancement

#936 fastly backend create: override host cannot be an empty string
  pkg/commands/backend/backend_test.go
  pkg/commands/backend/create.go
Labels: bug

#940 fix(kvstoreentry): support JSON output for bulk processing
  pkg/commands/kvstoreentry/create.go
Labels: bug

#943 feat(compute/hashfiles): add hash-files subcommand
  pkg/app/commands.go
  pkg/commands/compute/deploy.go
  pkg/commands/compute/deploy_test.go
  pkg/commands/compute/hashfiles.go
  pkg/commands/compute/hashsum.go
  pkg/manifest/file.go
Labels: enhancement, deprecated
