Repository fastly/cli, pull requests merged in 2023-01, with the labels that each got.

#750 build(makefile): add goreleaser target for testing builds locally
  Makefile
Labels: enhancement

#751 fix(pkg/commands/vcl/snippet): set default dynamic value
  pkg/commands/vcl/snippet/create.go
Labels: bug

#762 feat(objectstore): add `--json` support to keys/list subcommands
  pkg/commands/objectstore/insert.go
  pkg/commands/objectstore/keys.go
  pkg/commands/objectstore/list.go
  pkg/text/objectstore.go
Labels: enhancement, breaking

#763 feat(objectstore/get): implement --json flag for getting key value
  pkg/commands/objectstore/getkey.go
Labels: enhancement, breaking

#764 feat(compute/deploy): add Object Store to manifest `[setup]`
  pkg/commands/compute/compute_mocks_test.go
  pkg/commands/compute/deploy.go
  pkg/commands/compute/deploy_test.go
  pkg/commands/compute/setup/object_store.go
  pkg/manifest/manifest.go
Labels: enhancement

#765 feat(compute/build): support locating language manifests outside project directory
  pkg/commands/compute/build_test.go
  pkg/commands/compute/language_assemblyscript.go
  pkg/commands/compute/language_go.go
  pkg/commands/compute/language_javascript.go
  pkg/commands/compute/language_rust.go
  pkg/commands/compute/language_toolchain.go
Labels: enhancement

#758 feat(compute/serve): implement --watch-dir flag
  pkg/commands/compute/compute_test.go
  pkg/commands/compute/serve.go
  pkg/errors/errors.go
Labels: enhancement

#767 fix(setup): object_store needs to be linked to service
  go.mod
  go.sum
  pkg/api/interface.go
  pkg/commands/compute/compute_mocks_test.go
  pkg/commands/compute/deploy.go
  pkg/commands/compute/deploy_test.go
  pkg/commands/compute/setup/object_store.go
  pkg/mock/api.go
Labels: bug

#717 Add Secret Store support
  pkg/api/interface.go
  pkg/app/commands.go
  pkg/app/run.go
  pkg/app/run_test.go
  pkg/cmd/flags.go
  pkg/commands/secretstore/createsecret.go
  pkg/commands/secretstore/createstore.go
  pkg/commands/secretstore/deletesecret.go
  pkg/commands/secretstore/deletestore.go
  pkg/commands/secretstore/describesecret.go
  pkg/commands/secretstore/describestore.go
  pkg/commands/secretstore/doc.go
  pkg/commands/secretstore/flags.go
  pkg/commands/secretstore/helper_test.go
  pkg/commands/secretstore/json.go
  pkg/commands/secretstore/listsecrets.go
  pkg/commands/secretstore/liststores.go
  pkg/commands/secretstore/root_secret.go
  pkg/commands/secretstore/root_store.go
  pkg/commands/secretstore/secret_test.go
  pkg/commands/secretstore/store_test.go
  pkg/mock/api.go
  pkg/sync/sync.go
  pkg/testutil/assert.go
  pkg/text/secretstore.go
  pkg/text/text.go
Labels: enhancement, DO NOT MERGE YET

#774 fix(objectstore/get): output value unless verbose/json flag passed
  pkg/commands/objectstore/getkey.go
Labels: bug

#775 refactor(compute/deploy): reduce size of Exec()
  pkg/commands/compute/deploy.go
  pkg/commands/compute/setup/domain.go
  pkg/undo/undo.go
Labels: clean-up

#778 fix(compute/init): add warning for paths with spaces
  pkg/commands/compute/init.go
Labels: bug

#779 refactor(compute/deploy): add messaging to explain [setup] is a one-time-shot
  pkg/commands/compute/deploy.go
Labels: enhancement

#776 fix(compute/deploy): clean-up new service creation on-error
  pkg/commands/compute/deploy.go
  pkg/commands/compute/deploy_test.go
Labels: bug
