Repository fastly/cli, pull requests merged in 2024-03, with the labels that each got.

#1142 fix(compute/build): avoid persisting old metadata
  pkg/commands/compute/build_test.go
  pkg/commands/compute/language_toolchain.go
Labels: bug

#1145 refactor(app): update list of commands that require a token
  pkg/app/run.go
  pkg/commands/compute/deploy.go
Labels: enhancement, clean-up

#1150 fix(compute/serve): avoid wasm validation when --file is set
  pkg/commands/compute/build.go
  pkg/commands/compute/language_assemblyscript.go
  pkg/commands/compute/language_go.go
  pkg/commands/compute/language_javascript.go
  pkg/commands/compute/language_other.go
  pkg/commands/compute/language_rust.go
  pkg/commands/compute/language_toolchain.go
  pkg/commands/compute/serve.go
Labels: bug

#1155 build: bump go-fastly to v9.0.1
  go.mod
  go.sum
Labels: dependencies

#1156 build(deps): bump actions/download-artifact and actions/upload-artifact from 3 to 4
  .github/workflows/pr_test.yml
Labels: dependencies, go, github_actions

#1160 fix(compute/serve): let wasm-tools fail more gracefully
  pkg/commands/compute/build.go
  pkg/global/global.go
  pkg/testutil/args.go
Labels: bug

#1161 fix(text): deref pointers
  pkg/text/configstore.go
  pkg/text/service.go
Labels: bug

#1162 refactor: avoid duplicate path strings
  pkg/commands/compute/build.go
  pkg/commands/compute/language_assemblyscript.go
  pkg/commands/compute/language_go.go
  pkg/commands/compute/language_javascript.go
  pkg/commands/compute/serve.go
Labels: enhancement, clean-up

#1164 Update all URLs for developer.fastly.com to their new forms.
  .fastly/help/README.md
  CHANGELOG.md
  DOCUMENTATION.md
  README.md
  RELEASE.md
  pkg/app/metadata.json
  pkg/app/run.go
  pkg/app/usage.go
  pkg/commands/aclentry/update.go
  pkg/commands/authtoken/create.go
  pkg/commands/compute/build.go
  pkg/commands/compute/hashfiles.go
  pkg/commands/compute/init.go
  pkg/commands/compute/language_assemblyscript.go
  pkg/commands/compute/language_go.go
  pkg/commands/compute/language_toolchain.go
  pkg/commands/compute/serve.go
  pkg/commands/compute/testdata/build/javascript/package.json
  pkg/commands/compute/testdata/build/javascript/src/index.js
  pkg/commands/compute/testdata/init/fastly-viceroy-update.toml
  pkg/commands/configstore/doc.go
  pkg/commands/configstoreentry/doc.go
  pkg/commands/resourcelink/doc.go
  pkg/commands/secretstore/doc.go
  pkg/commands/secretstoreentry/create.go
  pkg/commands/secretstoreentry/doc.go
  pkg/commands/serviceauth/create.go
  pkg/commands/vcl/condition/create.go
  pkg/errors/errors.go
  pkg/errors/remediation_error.go
  pkg/manifest/file.go
  pkg/manifest/manifest.go
  pkg/manifest/setup.go
  pkg/manifest/testdata/fastly-viceroy-update.toml
Labels: enhancement, clean-up

#1166 feat(logging/scalyr): add project-id
  go.mod
  go.sum
  pkg/commands/compute/init_test.go
  pkg/commands/logging/scalyr/create.go
  pkg/commands/logging/scalyr/describe.go
  pkg/commands/logging/scalyr/list.go
  pkg/commands/logging/scalyr/scalyr_integration_test.go
  pkg/commands/logging/scalyr/scalyr_test.go
  pkg/commands/logging/scalyr/update.go
  pkg/mock/client.go
Labels: enhancement

#1169 fix(stats/historical): avoid runtime SIGSEGV
  pkg/commands/stats/historical.go
Labels: bug
