Repository fastly/cli, pull requests merged in 2024-07, with the labels that each got.

#1239 feat: add debug-mode around all network requests
  pkg/api/undocumented/undocumented.go
  pkg/app/run.go
  pkg/auth/auth.go
  pkg/commands/compute/deploy.go
  pkg/commands/compute/init.go
  pkg/commands/compute/init_test.go
  pkg/commands/logtail/root.go
  pkg/debug/debug.go
  pkg/github/github.go
Labels: enhancement

#1246 fix(compute/serve): don't fail the serve workflow if github errors
  pkg/commands/compute/serve.go
Labels: bug

#1249 Test case refactor
  pkg/commands/ip/ip_test.go
  pkg/commands/profile/profile_test.go
  pkg/commands/ratelimit/ratelimit_test.go
  pkg/testutil/scenarios.go
Labels: clean-up
